openapi: 3.0.1
info:
  title: WEMDE DispatchInstruction
  version: '3.0'
  x-origin:
  - format: openapi
    source: AEMO API Management developer portal
    url: https://dev.aemo.com.au/developer/apis/wemde-dispatchinstruction-external-v1/operations?api-version=2022-04-01-preview
servers:
- url: https://api-gwy-prd.aemo.local/WEM/v1/dispatchInstruction
- url: https://api-gwy-prd.aemo.local/WEM/v1/dispatchInstruction
paths:
  /dispatchInstruction:
    get:
      operationId: retrievesTheRecentDispatchInstructionForEachParticipant
      summary: Retrieves the recent dispatch instruction for each participant
      tags:
      - WEMDE DispatchInstruction
      description: Retrieves the recent dispatch instruction for each participant
      parameters:
      - name: facilityCode
        in: query
        required: false
        schema:
          type: string
      - name: updatedRecordsOnly
        in: query
        required: false
        schema:
          type: boolean
          default: 'false'
      - name: x-initiatingParticipantId
        in: header
        required: true
        schema:
          type: string
        description: The id of the Initiating Participant
      - name: x-market
        in: header
        required: true
        schema:
          type: string
        description: The id of the market
      responses:
        '200':
          description: Success
          content:
            text/plain:
              example: ''
            application/json:
              example:
                errors:
                - {}
                warnings:
                - {}
                infos:
                - {}
                transactionId: string
                data:
                  dispatchInstructionId: string
                  dispatchInterval: string
                  issuedTime: string
                  data:
                  - facilityCode: string
                    sentOut:
                      dispatchTarget: 0
                      dispatchCap: 0
                    asGenerated:
                      dispatchTarget: 0
                      dispatchCap: 0
                    rampRate: 0
                    regulationRaiseEnablementQuantity: 0
                    regulationLowerEnablementQuantity: 0
                    contingencyRaiseEnablementQuantity: 0
                    contingencyLowerEnablementQuantity: 0
                    rocofEnablementQuantity: 0
            text/json:
              example:
                errors:
                - {}
                warnings:
                - {}
                infos:
                - {}
                transactionId: string
                data:
                  dispatchInstructionId: string
                  dispatchInterval: string
                  issuedTime: string
                  data:
                  - facilityCode: string
                    sentOut:
                      dispatchTarget: 0
                      dispatchCap: 0
                    asGenerated:
                      dispatchTarget: 0
                      dispatchCap: 0
                    rampRate: 0
                    regulationRaiseEnablementQuantity: 0
                    regulationLowerEnablementQuantity: 0
                    contingencyRaiseEnablementQuantity: 0
                    contingencyLowerEnablementQuantity: 0
                    rocofEnablementQuantity: 0
        '400':
          description: Bad request
          content:
            application/json:
              examples:
                missingHeader:
                  summary: Missing mandatory HTTP header parameter
                  value:
                    transactionId: 61361d96-f20d-43a7-bkdf-59b35fab9b13
                    data: {}
                    errors:
                    - code: '400'
                      title: Missing mandatory HTTP header parameter
                      detail: Mandatory HTTP header <headerName> is missing
                      source: null
        '401':
          description: Unauthorized
          content:
            application/json:
              examples:
                unauthorized:
                  summary: Unauthorized
                  value:
                    transactionId: 9a8e902a-ed40-45f3-b075-7a644b12947f
                    data: {}
                    errors:
                    - code: '401'
                      title: Unauthorized
                      detail: Unauthorized
                      source: null
                initiatingParticipantIdMismatch:
                  summary: x-initiatingParticipantId does not match with participant id associated with
                    certificate
                  value:
                    transactionId: 9a8e902a-ed40-45f3-u475-7a644b12947f
                    data: {}
                    errors:
                    - code: '401'
                      title: Unauthorized
                      detail: x-initiatingParticipantId does not match with participant id associated
                        with certificate
                      source: null
        '403':
          description: Forbidden
          content:
            text/plain:
              example: ''
            application/json:
              example:
                transactionId: string
                data: {}
                errors:
                - code: 0
                  title: string
                  detail: string
                  source: string
            text/json:
              example:
                transactionId: string
                data: {}
                errors:
                - code: 0
                  title: string
                  detail: string
                  source: string
        '404':
          description: Not Found
          content:
            text/plain:
              example: ''
            application/json:
              examples:
                resourceNotFound:
                  summary: Resource Not Found
                  value:
                    transactionId: 61361d96-f09d-43a7-babf-59b35fab9b13
                    data: {}
                    errors:
                    - code: '404'
                      title: Not Found
                      detail: Resources for the endpoint URI not found. Endpoint URI:<URI>
                      source: null
            text/json:
              example:
                transactionId: string
                data: {}
                errors:
                - code: 0
                  title: string
                  detail: string
                  source: string
        '405':
          description: Method not allowed
          content:
            application/json:
              examples:
                methodNotAllowed:
                  summary: Method Not Allowed
                  value:
                    transactionId: 61361d96-z20d-43a7-babf-59b35fab9b13
                    data: {}
                    errors:
                    - code: '405'
                      title: Method Not Allowed
                      detail: 'Input request HTTP method is <invokedMethod> but operation <operationURI>
                        accepts only: [<operationMethod>]'
                      source: null
        '413':
          description: Payload Too Large
          content:
            application/json:
              examples:
                payloadTooLarge:
                  summary: Payload Too Large
                  value:
                    transactionId: dc6826bc-1c0d-498b-b474-2b231910860c
                    data: {}
                    errors:
                    - code: '413'
                      title: Payload Too Large
                      detail: Maximum allowed size for the <request/response> body is <payload size limit>
                        bytes (<size limit> MB). This <request/response> has size of <number of bytes>
                        bytes
                      source: null
        '422':
          description: Client Error
          content:
            text/plain:
              example: ''
            application/json:
              example:
                transactionId: string
                data: {}
                errors:
                - code: 0
                  title: string
                  detail: string
                  source: string
            text/json:
              example:
                transactionId: string
                data: {}
                errors:
                - code: 0
                  title: string
                  detail: string
                  source: string
        '429':
          description: Too many request
          content:
            application/json:
              examples:
                tooManyRequests:
                  summary: Too Many Requests
                  value:
                    transactionId: 63361d96-f20d-43a7-babf-59b35fab9b13
                    data: {}
                    errors:
                    - code: '429'
                      title: Too Many Requests
                      detail: Number of inbound requests exceeded the throttling limits; try after sometime
                      source: null
        '500':
          description: Application Unavailable or Server Error
          content:
            text/plain:
              example: ''
            application/json:
              examples:
                applicationUnavailable:
                  summary: Application Unavailable
                  value: ''
            text/json:
              example:
                transactionId: string
                data: {}
                errors:
                - code: 0
                  title: string
                  detail: string
                  source: string
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
- {}
- apiKeyHeader: []
- apiKeyQuery: []
tags:
- name: WEMDE DispatchInstruction
  description: WEMDE DispatchInstruction
